version: '3.8'

services:
  web:
    # Берем Dockerfile из каталога app
    build: ./lct_cv
    # Запускаем тестовый сервер
    command: python ai_detection.py
    # куда будут помещены данные из каталога app
    volumes:
      - ./lct_cv/:/usr/src/lct_cv/
    # Файл содержащий переменные для контейнера
    env_file:
      - ./.env